[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

# for threading (requires nightly):
# rustflags = ["-C", "target-feature=+simd128,+atomics,+bulk-memory,+mutable-globals"]
# [unstable]
# build-std = ["std", "panic_abort"]
